### ISSUE TITLE
Handle Out-of-Order Messages in Presign

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#11]
The presign protocol does not currently implement the out-of-order message handling code used in the other protocols. Tests should also be updated to randomize presign message ordering

**Comment by indomitableSwan** [comment]
Can you be more specific as to how this is handled in the other protocols? Ideally tickets are descriptive enough for other developers to take on.

**Comment by tyurek** [comment]
Sure. src/participant.rs defines a ProtocolParticipant trait which implements some convenience functions. Of note here are stash_message and fetch_messages which are used to store messages that arrive before they're needed and later retrieve them when appropriate. The presign Participant would need to implement this train and make use of these functions. The success of this can be tested by randomizing the order in which messages are retrieved from a message queue
