### ISSUE TITLE
Write tests for PiFacProof

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#113]
A `PiFacProof` has nine elements that must satisfy five different constraints. Some ideas for tests:
- Swap each of the proof elements for a different, random element (of the correct type). Proof shouldn't verify.
- Bad inputs: try with small p, large q, and vice-versa. The range checks should fail.
- Try verifying the proof with different setup or public parameters than were used to construct it.

Related issue: #47.

**Comment by gatoWololo** [comment]
Additional changes based on comments on #442:
- In `test_no_small_factors_proof_negative_cases`, the `correct_factors` lambda should "include the two cases where exactly one of p and q are incorrect."
- In `test_no_small_factors_proof_negative_cases` we test for:
```rust
let modulus = &small_p * &regular_sized_q;
let mixed_input = CommonInput::new(&setup_params, &modulus);
```
We test for a small `p` but we don't test for small q. Add small `q` out of range case.

**Comment by marsella** [comment]
More broadly, the `test_no_small_factors_proof_negative_cases` test should be broken up into smaller, more descriptive tests rather than being one monolithic test.

**Comment by marsella** [comment]
There are several tests in this module that don't test the correct thing. [See comment on #442](https://github.com/boltlabs-inc/tss-ecdsa/pull/442#discussion_r1269541638); in 3 different tests, the goal is to test a property of the proof itself -- if you provide secret input that does not meet the requirements of the proof, the proof should fail. These tests currently provide different common inputs at proving and verification time, so the proofs are failing because the challenge is different, not because the secrets are invalid.

**Comment by hridambasu** [comment]
The test_modulus_cannot_have_large_factors() test should be checked for whether the range check in the proof has "too large" factors than the regular sized factors, and not "too small" factors, despite the name of the proof might suggest otherwise.
