### ISSUE TITLE
Update Facebook-related descriptions

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#12]
Files like the code of conduct and contributing file should be updated to reflect the current situation at Bolt. Should file headers be updated too?

**Comment by indomitableSwan** [comment]
Anything Facebook-related should be updated. This would include headers, yes.

**Comment by gatoWololo** [comment]
Here is what must be done to comply with our licenses:
- [ ] Add a copyright notice to all our modified source files. (As Tom pointed out, at this point this is all files). The code is copyrighted by default when it is written, it is considered good practice to include the copy right notice. This can be added below the other copyright notice.
- [ ] Add a notice stating the source file has been modified.

We can get two birds with one stone by adding the following below notification to each file:
```
Modifications Copyright (c) 2022 [name of copyright owner]
```
This is probably `Bolt Labs LLP`. @indomitableSwan can you confirm the legal entity?

So our headers would look like:
```diff
// Copyright (c) Facebook, Inc. and its affiliates.
+ // Modifications Copyright (c) 2022 [name of copyright owner]
```
