### ISSUE TITLE
Fix sampling range in presigning

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#123]
In Presigning round 2, we draw `beta` and `beta_hat` from plus/minus `2^ell`. I think it should be `ell'` (that's `ELL_PRIME`). The protocol draws from fancy-J, which is defined in the Nota Bene on page 23.

- [ ] Double-check that this is actually a bug
- [ ] Fix it

**Comment by Ra1issa** [comment]
Small comment for posteriority: the NB is on page 25, and the range is 2^{l'+epsilon}

**Comment by marsella** [comment]
The paper actually has conflicting information about what the correct range for `beta` and `beta_hat` is. In Section 4.1, step 2 it's from `J_epsilon = 2^(ell' + epsilon)`. But in Figure 7 it's `J = 2^ell'`. I think `J` is the correct range:

`beta` and `beta_hat` are each used in an instance of the `PiAffG proof`. They're `y` in that proof writeup (Figure 15). The secret input for that proof has to be in plus/minus `2^ell'`. 

In general, the parameter epsilon is the "slackness" parameter for the soundness of range checks -- when you do a range check you take the value you care about and mask it with a mask and the challenge, so the thing you actually do a range check on might be bigger than your original range. So, you draw something from 2^ell, and then you verify it's in range in zk by checking the masked version is in 2^ell + epsilon.
