### ISSUE TITLE
Make Ring-Pedersen commitment abstraction

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#128]
Many proofs involve Ring-Pedersen commitments. Right now, these are computed manually throughout the protocol, using the `ZkSetupParameters` to hold the Ring-Pedersen parameters (as well as a proof that they are valid). Standard commitments and operations on commitments are computed manually in many places, which makes it (a) harder to recognize them as commitments and (b) easier to mis-compute at some point.

To complete this issue:
- [ ] make a Ring-Pedersen module with an appropriate API, documentation, and tests
- [ ] integrate the module into the protocol (this might be better spun out into a separate issue if the PR starts to get huge)

## Proposed solution
@amaloz wrote the following API for Ring-Pedersen commitments. This would replace manual / inline computations across all the protocols, and would replace any tuples `(N, s, t)`, such as the one in `ZkSetupParameters`, with a `RingPedersen` object.

```rust
pub(crate) struct RingPedersen {
    /// The RSA modulus.
    pub(crate) N: BigNumber,
    /// Ring-Petersen parameter `s`.
    pub(crate) s: BigNumber,
    /// Ring-Petersen parameter `t`.
    pub(crate) t: BigNumber,
}

#[derive(PartialEq)]
pub(crate) struct Commitment(BigNumber);

impl RingPedersen {
    /// Extracts a [`RingPedersen`] object from a [`PaillierDecryptionKey`].
    pub(crate) fn derive(sk: &PaillierDecryptionKey) -> Result<Self> {}

    /// Produces a Pedersen commitment $`s^a t^b`$ commiting to the values `a` and `b`.
    pub(crate) fn commit(&self, a: &BigNumber, b: &BigNumber) -> Commitment {}

    /// Produces a Pedersen commitment $`s^a t^b`$ for values $`a \in 2^{\text{range}_0}`$
    /// and $`b \in 2^{\text{range}_1}`$.
    pub(crate) fn commit_from_ranges(
        &self,
        range0: usize,
        range1: usize,
        rng: &mut (impl RngCore + CryptoRng),
    ) -> Result<(Commitment, BigNumber, BigNumber)> {
    }

    /// Combines two commitments with exponent `e` by computing $`\text{com}_0 \text{com}_1^{e}`$.
    pub(crate) fn combine(
        &self,
        com0: &Commitment,
        com1: &Commitment,
        e: &BigNumber,
    ) -> Result<Commitment> {
    }
}
```

**Comment by marsella** [comment]
I definitely like this approach! I have a couple questions about the expected usage though.

Typically, the `a` and `b` in Ring-Pedersen commitments are distinguished from each other, right? I have a loose recollection that one of them is the commitment randomness and one of them is the commitment value. Looking at the proofs more carefully, the `a` value (exponent on `s`) is the only one that is integrated into other aspects of a given proof (e.g. as an encrypted message value or a Schnorr commitment), so we might want an API like:
```rust
/// Produces a Pedersen commitment to the given value and the commitment randomness used to create it.
/// `s^value t^randomness mod N`
pub(crate) fn commit(&self, value: &BigNumber) -> (Commitment, BigNumber) {}
```

This isn't perfect because the commitment randomness needs to be drawn from various ranges. Staring a bit more at `PiAffG`, it looks like the commitment value and randomness are always drawn from related distributions: the value from plus/minus `2^k` and the randomness from plus/minus `(2^k) * N`, where `k` varies but `N` is always the Ring-Pedersen one.

If you like commitment randomness, we might lean into it and see if it makes sense to add a type and a `mask` function to compute e.g. `z3` and `z4` in `PiAffG` -- which follow the same pattern as the mask function you just wrote for two `PaillierNonce`s. If we go for that, we'll also need a `masked_commit` kind of method. 

Overall, I guess I see three kinds of commitments:
1. commit to a pre-existing input (e.g. `x` in PiAffg) with random commitment randomness - for proving
2. commit to a random input (e.g. `alpha` in PiAffg) with random commitment randomness - for masking while proving
3. commit to a pre-existing input and commitment randomness (e.g. `z1, z3` in PiAffg) - for verifying

I'm not sure that we want three different commitment methods (e.g. we could have one method to handle both 1 and 2).


Let me try to sketch out what I'm thinking:
```rust
struct CommitmentRandomness(BigNumber);
struct MaskedRandomness(BigNumber);

impl RingPedersen {
    /// Extracts a [`RingPedersen`] object from a [`PaillierDecryptionKey`].
    pub(crate) fn derive(sk: &PaillierDecryptionKey) -> Result<Self> {}

    /// Produces a Pedersen commitment $`s^a t^b`$ commiting to the values `a` and `b`.
    /// Used to verify proofs.
    pub(crate) fn commit_masked(&self, a: &BigNumber, b: &MaskedRandomness) -> Commitment {}

    /// Produce a Pedersen commitment to the given value, which must be drawn from the range plus/minus `2^range`.
    /// The commitment randomness will be sampled from plus/minus `2^range * self.N`.
    /// Used to generate proofs.
    pub(crate) fn commit(&self, value: &BigNumber, range: usize) -> (Commitment, CommitmentRandomness) {}

    /// Masks commitment randomness: mask + challenge * value.
    pub(crate) fn mask(value: CommitmentRandomness, mask: CommitmentRandomness, challenge: BigNumber) -> MaskedRandomness {}

    /// Combines two commitments with exponent `e` by computing $`\text{com}_0 \text{com}_1^{e}`$.
    pub(crate) fn combine(
        &self,
        com0: &Commitment,
        com1: &Commitment,
        e: &BigNumber,
    ) -> Result<Commitment> {
    }
}
```

This avoids any ordering issues e.g. sometimes we need to do Paillier operations with commitment values -- we can generate the value (e.g. `alpha` in PiAffg) and do the Paillier encryption and commitment in either order. And I think it gives us less room for mistakes that the more general `commit_from_ranges()`. Thoughts?

**Comment by amaloz** [comment]
I like it! Sadly though, it looks like `pifac` complicates things. This appears to be for two reasons:
1. A non-standard Pedersen commitment is constructed from an output commitment: `Q` is the output of a commitment and is then used to compute `T = Q^a t^r`.
2. Some of the ranges required are of the form `2^\ell * N_0`.
3. There's a nonstandard masked randomness computation of `\sigma_hat = \sigma - \nu p`.

The following takes care of Issue 1 (documentation to be improved, but hopefully you get the gist):
```rust
    /// Produces a Pedersen commitment to the given `value` using [`Commitment`] `com`.
    ///
    /// In more detail, the following is computed: `com^value t^r mod N` where `r` falls
    /// in the range `+/- 2^range * modulus`.
    pub(crate) fn commit_with_commitment(
        &self,
        com: &Commitment,
        value: &BigNumber,
        range: usize,
        modulus: &BigNumber,
        rng: &mut (impl RngCore + CryptoRng),
    ) -> (Commitment, CommitmentRandomness) {
    }

    /// Computes `com^value t^randomness mod N`.
    pub(crate) fn commit_masked_with_commitment(
        &self,
        com: &Commitment,
        value: &BigNumber,
        randomness: &MaskedRandomness,
    ) -> Commitment {
    }
```
I can also add dedicated functions for the computation of `sigma` and `sigma_hat`, but it's starting to look a lot less clean than I was hoping. I guess this is where we weigh API cleanliness with misuse resistance: we can have general APIs that allow committing to arbitrary values, which will clean up the API but be more error-prone, or have tightened down APIs that are really use-once (e.g., these are only used in `pifac` as far as I can tell). Thoughts?

**Comment by marsella** [comment]
Ahh, drat. How would you feel about a submodule that does all the weird stuff for `pifac`? It's different at almost every step. It still seems useful to me to keep all the RP stuff together and labelled for auditing purposes, and to keep the types meaningful. But I can see the silliness of having a big, single-use API with a bunch of exceptions.

**Comment by amaloz** [comment]
@marsella Take a look at the draft PR #144 and let me know what you think! It includes the full API with the above specialized functions for `pifac`, but I'm certainly open to removing those if we so desire.
