### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#13]
Get rid of all .unwrap() calls in the library and replace them with errors and question marks.

**Comment by tyurek** [comment]
Additionally we should replaces asserts with errors as mentioned by Omar here: https://github.com/boltlabs-inc/tss-ecdsa/pull/15#discussion_r1002150679

**Comment by gatoWololo** [comment]
To add to this. The code has a lot of uses of stringly typed error variants. E.g. `bail!("Cannot produce a signature without including shares"),`.

We should understand who these are used replace them with a more appropriate error handling method.
