### ISSUE TITLE
Reduce ownership requirements for proof inputs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#135]
The `Proof` trait has two associated types that describe the secret and common inputs the prover provides to create the proof (the verifier also uses the common inputs to verify). These types are necessary to create the proof, but their components do not become _part_ of the proof. So, ideally, the calling code would not have to clone or transfer ownership of the common input fields in order to create a proof.

Right now, the prove method takes the `Self::CommonInput` field by reference, which makes sense. However, in order to _create_ the common input, they need to take ownership of each of its fields. This results in a lot of cloning. The goal of this issue is to limit ownership takeover of fields that are not actually components of the final `Proof`.

## Proposed Solution
@gatoWololo and I talked about this. He proposed using generic associated types to allow the common input to have a lifetime parameter without having to attach that lifetime to the final `Proof`. GATs let you keep the lifetime parameter for the associated type and the methods that use that associated type, but not be forced to stick it onto the type implementing the trait.

Minimal example (by @gatoWololo )
```rust
trait Proof: Sized {
    type CommonInput<'a>;
    type ProverSecret;

    fn prove<'a>(input: Self::CommonInput<'a>) -> Result<Self, ()>;
    fn verify<'a>(&self, input: Self::CommonInput<'a>) -> Result<(), ()>;
}

struct Foo;
struct FooInput1;
struct FooInput2;

struct FooInputs<'a> {
    foo1: &'a FooInput1,
    foo2: &'a FooInput2,
}
struct FooSecret;

impl Proof for Foo {
    type CommonInput<'a> = FooInputs<'a>;
    type ProverSecret = FooSecret;

    fn prove<'a>(input: Self::CommonInput<'a>) -> Result<Self, ()> {
        // Verify things with `input.foo1` and `input.foo2` here...

        Ok(Foo {})
    }

    fn verify<'a>(&self, input: Self::CommonInput<'a>) -> Result<(), ()> {
        todo!()
    }
}

fn use_it() {
    let foo1 = FooInput1;
    let foo2 = FooInput2;
    let common_input = FooInputs { foo1: &foo1, foo2: &foo2 };
    let foo = Foo::prove(common_input).unwrap();

    let common_input = FooInputs { foo1: &foo1, foo2: &foo2 };
    foo.verify(common_input).unwrap();
}
```

**Comment by amaloz** [comment]
One additional thought: Should `verify` consume `self` rather than take it by reference? Put another way, are there settings where we need to verify the same proof multiple times? If not, it might be a cleaner API to have `verify(self, input: ...)`.

**Comment by gatoWololo** [comment]
Due to the necessary changes to modules we will do this in parts:
- [ ] `PiAffgProof`
- [ ] `PiEncProof`
- [ ] `PiLogProof`
- [ ] `PiModProof`
- [ ] `PiPrmProof`
- [ ] `PiSchProof`
