### ISSUE TITLE
Encode fixed parameters into proof contexts

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#142]
Each subsession has a set of parameters that are known to all parties at the beginning of the subsession. These parameters need to be integrated into each proof generated over the course of the subsession. In particular, we need:

- List of participants `P`. Used in all subprotocol proofs. `P`. #239
- Public parameters for ECDSA `(G, q, g)` (fixed across the implementation). Used in all subprotocol proofs. #240
- Public parameters for Paillier (fixed across the implementation). Used in all subprotocol proofs. #240
- Agreed upon parameters from a KeyGen instance: `(rid, X)` (where `X` is a vector of participant public key shares). Used in all signing operations. #243
- Agreed upon parameters from a run of AuxInfo: `(N, s, t)` (where again, these are vectors of participant Paillier public keys and participant-chosen Ring-Pedersen params). Used in all signing operations (presign and signing). #241

These parameter values must be incorporated into every proof in the subsession.

## Completion criteria
- [ ] Design an approach to encode and pass these values to the proofs
- [ ] Implement the approach, including incorporation into proof challenge generation
- [ ] Add any relevant unit tests.

## Problems for later
- This issue should not try to solve the problem of where agreement on participant identifiers comes from. Right now, they are passed to a new `Participant` when it's created, and we won't try to change that.The participant IDs need to have a canonical order that includes all IDs (self + others). 

## Related issues
This is a subset of #4.

**Comment by indomitableSwan** [comment]
We shouldn't just ignore `...`. In particular, the above list isn't all the public parameters for the scheme, is it? e.g., where do establish the Paillier parameters?

**Comment by indomitableSwan** [comment]
Can we rewrite to include a more specific list for each protocol? In particular, "Everything KeyGen" is a bit imprecise in terms of language; maybe it's just me, but I had to read that twice. I also believe there is an error in the above with respect to `X` (see comment in list below).

It might be helpful to separate things out conceptually (if nothing else, for the documentation). e.g.,
- Public parameters for ECDSA (fixed across the implementation). Used in all subprotocol proofs.
- Public parameters for Paillier (fixed across the implementation). Used in all subprotocol proofs.
- Agreed upon parameters from a KeyGen instance/previous run of AuxInfo: `rid`, `X` (where `X` is a vector of participant public key shares, _not_ the associated ECDSA public key that is _formed_ from said shares). Used in all signing operations.
- Agreed upon parameters from a run of AuxInfo: `N`, `s`, `t` (where again, these are vectors of participant Paillier public keys and participant-chosen Ring-Pedersen params). Used in all signing operations.

**Comment by marsella** [comment]
@indomitableSwan I updated the issue description as you suggested, but I have two questions:
 
> Public parameters for Paillier (fixed across the implementation)

I don't know what these are. The Paillier keys themselves are chosen in AuxInfo as you noted and are not fixed across the implementation. The Paillier key size is defined by the public ECDSA parameters.

> Agreed upon parameters from a KeyGen instance/previous run of AuxInfo: `rid, X`

What do you mean by "previous run of AuxInfo"? These parameters are outputs from KeyGen. `X` could change if we do key refresh, but we're don't. Aux-info alone doesn't change `X`. As far as I can tell, `rid` never changes.

**Comment by indomitableSwan** [comment]
> @indomitableSwan I updated the issue description as you suggested, but I have two questions:
> 
> > Public parameters for Paillier (fixed across the implementation)
> 
> I don't know what these are. The Paillier keys themselves are chosen in AuxInfo as you noted and are not fixed across the implementation. The Paillier key size is defined by the public ECDSA parameters.
> 

I think we're talking past each other a bit here. I think it's wise to encode the size of the modulus used for Paillier here, regardless of what the paper may say on this question.

> > Agreed upon parameters from a KeyGen instance/previous run of AuxInfo: `rid, X`
> 
> What do you mean by "previous run of AuxInfo"? These parameters are outputs from KeyGen. `X` could change if we do key refresh, but we're don't. Aux-info alone doesn't change `X`. As far as I can tell, `rid` never changes.

yes, I meant AuxInfo as defined in the paper, i.e., with key refresh. (I know that we don't want to implement it that way, sorry.)

**Comment by marsella** [comment]
This issue is being subsumed by the linked issues as well as #237 and #238 to build out infrastructure and #242 and #243 to fix a related bug.
