### ISSUE TITLE
Convert all verify proof errors to logs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#155]
The proof verification error (`InternalError::FailedToVerifyProof`) includes a string parameter that describes how the proof failed to verify. This string should be removed from the error type and put into logs instead. The logs should also include _which_ proof failed (this might be captured by the `tracing` library's context, but double-check).

**Comment by gatoWololo** [comment]
The convention we are going for is having our logging contexts map to functions. So as long as we tag the function with the `#[instrument]` macro + adding the `error!("...")` events it should point to which proof failed at the function granularity. Would this be sufficient?

**Comment by marsella** [comment]
Yep, that sounds perfect!
