### ISSUE TITLE
Optimization: Add a "protocol done" entry to storage

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#160]
Previously, our end to end system runs progress by repeatedly polling functions like `is_keygen_done()` in order to determine when to start the next protocol or mark the run as finished. These `is_*_done` functions used to work by checking `Storage` for all of the necessary outputs for that instance. In `is_auxinfo_done` and `is_keygen_done`, it involves attempting to retrieve data corresponding to each other `Participant` in the protocol. 

With #235, these external API endpoints were removed, so now the calling application has to track whether a `Participant` has returned output to know whether they've finished.

It would be nicer to re-add the public API method and add a "progress" entry of some kind to a `Participant`'s intermediate storage to indicate whether the protocol is done (and perhaps later, to indicate at which step in the protocol the `Participant` is).

- [x] Add a storage entry with a `TypeTag` to indicate protocol status for each `Participant` type.
- [x] Modify auxinfo, keygen, and presign code to initialize the status to "not done" and update it to "done" at the appropriate time
- [x] Add an `is_done` or `status` method to `ProtocolParticipant` and implement it by checking storage
- [x] Update tests for each participant to assert that `is_done` passes only if the participant has returned output
- [x] Update `test_run_protocol` and e2e benchmarks to condition on `is_done` instead of checking for output (you could still check that the protocol is done IFF the participant has returned output in the test).

**Comment by marsella** [comment]
I think this makes sense! A couple thoughts:
- We'll want to be careful about making sure we only set this when we're definitely done, e.g. checking the conditions from the `is_*_done` functions before setting the flag
- Per comment in #152, I think it might be useful to have this field be a general status enum, rather than just a bool for is/isn't done (e.g. we might update the status after each round). I don't think this issue should add every status update, but keep that extension in mind when you choose a representation for the stored type.

**Comment by marsella** [comment]
#231 started to address this but we ultimately decided that PR introduced an awkward intermediary state and closed it in favor of #235. 235 does not address this at all, so we'll put it back up for grabs.

**Comment by amaloz** [comment]
A couple thoughts on this:
> - [ ] Add a storage entry with a TypeTag to indicate protocol status for each Participant type.

In lieu of this I'm using a `Status` enum a la Marcella's comment

> We'll want to be careful about making sure we only set this when we're definitely done, e.g. checking the conditions from the is_*_done functions before setting the flag

I can double check these, but is there any reason that outputting `ProcessOutcome::Terminated` would _not_ equate to a done protocol execution?
