### ISSUE TITLE
Research how session ids are "typically" handled

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#165]
Unique session IDs are a hallmark of UC-secure proofs. Surely, then, other people have implemented proofs and generated some process for creating and distributing session IDs. Look into other UC-secure protocol implementations and see if there's any general guidance for this. Log your findings here.

Estimate is 2 because this needs to be time-bound!

Completion criteria:
- [x] Put any relevant notes about how other people do this here
- [x] Write out any solutions you think are potentially appropriate for us

**Comment by Ra1issa** [comment]
After some investigation into what UC typically means by session ids, it seems that the main property that we need is global uniqueness, i.e. that no two instances use the same session ids. The tss-ecdsa protocol does not seem to use these ids for anything beyond identifying sessions and their corresponding data.

UC-papers will typically construct these session ids by using shared parameters among parties, the party ids, the protocol description etc. By doing this, they avoid any issue of consensus and Byzantine agreement. 

However this is not the only way that we can create globally unique identifiers if we are willing to assume a trusted party or are okay with dealing with questions of consensus over these ids in the presence of corrupt parties.

In either case, for the time being we can assume that there exist some UC-mechanism that generates these session ids and passes them to the tss-ecdsa protocol.

**Comment by indomitableSwan** [comment]
Closing with the additional comment that we have some internal notes to capture more specifics on this topic, as outlined by the issue description.
