### ISSUE TITLE
Delete local storage after keygen runs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#170]
Right now, at the completion of an keygen protocol run, the participants copy over all important details into long-term storage, but don't delete intermediate values from local storage. These values are no longer useful or referenced (as long as we don't implement identifiable abort) so we can get rid of them. 

This issue does not aim to address what to do with local storage at the termination of an unsuccessful run.

## Proposed solutions
I think all stored items for a given protocol run will be tagged with the `message.id` field, so you should be able to query on that and delete everything associated with it. If you want to be more cautious about potential session ID overlaps, you could also check against the storage type and only delete the ones that were added in keygen (you'll have to search the protocol to figure out what those are).

## Completion criteria
- [ ] Delete local storage for given protocol run at the successful completion of the run
- [ ] Update any relevant documentation to log the deletion behavior of the `KeyGenParticipant`
- [ ] Derive `ZeroizeOnDrop` and maybe `Zeroize` on any secret types stored in keygen
- [ ] Add a test that local storage is properly deleted after a successful run (maybe this is another assert in the existing run-keygen test)

**Comment by tyurek** [comment]
While implementing these, it might be worth looking into the [zeroize crate](https://docs.rs/zeroize/latest/zeroize/) to ensure that the deleted data is zeroed out. I think this doesn't matter yet, since we're still keeping the main secrets around, but it might be worth making the deletions zero out memory if we're writing functions to delete data, so that we don't forget about this later

**Comment by marsella** [comment]
> While implementing these, it might be worth looking into the [zeroize crate](https://docs.rs/zeroize/latest/zeroize/) to ensure that the deleted data is zeroed out. I think this doesn't matter yet, since we're still keeping the main secrets around, but it might be worth making the deletions zero out memory if we're writing functions to delete data, so that we don't forget about this later

Good call, I added this to the criteria list.

**Comment by marsella** [comment]
Closing this because it will be obviated by #216 and friends.

I added the zeroize-on-drop stuff to #163.
