### ISSUE TITLE
Add a method for calling application to clean up local storage

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#172]
As long as we don't have identifiable abort implemented, local storage from unsuccessful protocol runs does not have a way to get deleted. Right now, it will just sit in memory forever. We should do something better than that!

## Proposed solutions
I think the simplest approach is to add a method on `Participant` that lets the calling application delete the local storage for a given session ID. They can decide when to do this -- maybe after a certain amount of time has passed without receiving a message for that protocol, or after getting an error back from processing a message on that protocol.

A more limited but misuse-resistant approach might add some flag to local storage that is set if a protocol fails with an error. Then the calling application could request clean-up of all protocols that errored out. However, this wouldn't catch the case where a _different_ participant saw an error and stopped sending messages, but this participant never had a problem (they just stopped receiving messages and don't know whether it was network failure or protocol error or what).

Or, we could put a timestamp on every field in local storage and only give the calling application the power to "delete old messages" for some definition of "old" of their choice. 

## Closing criteria
- [ ] Decide what an appropriate approach is
- [ ] Implement it
- [ ] Test it

**Comment by gatoWololo** [comment]
I can expand thoughts on what the implementation should look like:
- Currently our storage is a HashMap(Vec<u8>, Vec<u8>). Where the keys are serialized `StorableIndex` and the values are serialized types which are different based on what is being stored. A `StorableIndex` is just a 3-tuple of `(storable_type, identifier, participant)`. Where the `identifier` is the session ID for this subprotocol.
- Add a method to `Storage`: `delete_session(&mut self, id: Identifier)`. This method takes the proper `session ID` and iterates through all entries in the `HashMap` deleting any where the `id` argument to `delete_session` matches the `identifier` tuple member.

We do not have a way to return all KV pairs where identifier matches, so we do a linear scan through the `HashMap` similarly, our keys are stored serialized. So you will need to deserialize the keys back into a `StorableIndex` to compare the stored `identifier` against the `id` argument.

@marsella Given that the local storage will change after #181 and friends (#183...#185) is it worth implementing this now?

**Comment by marsella** [comment]
Good call, let's shelve this until we have a more finalized public API. We might end up handling this scenario with timeouts on participants or something else, and it doesn't seem worthwhile to spend a bunch of energy with the current storage model.
