### ISSUE TITLE
Change `BroadcastParticipant` to use local `StorageType`

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#200]
- [ ] Add a local `StorageType` to `broadcast/participant.rs` and move appropriate `StorageType` values here
- [ ] Use local `StorageType` throughout `BroadcastParticipant`

**Comment by marsella** [comment]
@amaloz This still needs to be done, right? I don't think `BroadcastSet` belongs in persistent storage.

**Comment by amaloz** [comment]
Yep! I got distracted by #181 and let this one slip. I'll work on it now :-)
