### ISSUE TITLE
Update public API to return output

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#203]
The public API for the library is dominated by the driver method `process_single_message`, which takes a message and returns any outgoing messages that its processing produced. If processing the message results in the completion of protocol, it should also return the output of that protocol.

This will shift the burden of maintaining state onto the calling application -- for us, that means the network example and the end-to-end benchmarks. In this issue, we're not going to pass the outputs to anything yet (there will be a separate issue to update the driver method to take inputs). Use them to check any conditions that are appropriate at this point, but don't build an infrastructure to maintain them; that will be in a separate issue. 

It will also have to tie the output to the session to which it belongs.

## Proposed solution
Return an enum that captures the different kinds of possible outputs. The driver method currently executes all the protocols, so the `ProcessOutput` type from #?? would have to have some kind of secondary enum as its parameter to differentiate between them. It seems nicer to just separate output and messages for now.

:warning: This suggestion doesn't tie the output back to the session ID!
```rust
enum Output {
    None,
    AuxInfo(Vec<AuxInfoPublic>, AuxInfoPrivate),
    Keygen(...),
    Presign(PresignRecord),
    Sign(SignatureShare), // not sure about this one
}
```
As a bonus, returning this output should let us get rid of some the `is_*_done` queries, since the caller can just check if they got output for the protocol in question.

## Completion criteria
- [x] Design an appropriate output type (or use the one suggested)
- [x] Update `process_single_message` to return that type
- [x] Update the networking example to receive output and use it to decide whether to send notifications
- [x] Update the e2e example to receive output
- [x] Update the tests to receive output and add any relevant checks

**Comment by gatoWololo** [comment]
We will be changing the functions a lot. I find the current networking example complicated and I don't think it makes for a very good example. I'm not sure if it is worth the maintenance burden to iterate with all our changes. I would propose deleting and coming up with a simpler example?

**Comment by marsella** [comment]
Let's touch base about what a simpler example would look like. I feel like it's better to have some example than no example, and I don't want to pull out the network example, then get caught up in other API things and postpone the new example indefinitely.

At least for this issue, the changes to the network example are minimal. They'll be more substantial in #205, because at that point we'll have to actually build in some storage interface.
