### ISSUE TITLE
Improve code quality in keygen

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#207]
This issue collects some code quality suggestions found while doing #194. The primary goal is to contain the internal API for the `keyshare` module.

- [x] Make all fields in `keyshare.rs` (public curve point, private share) read-only
- [x] Move key share generation functions to `keyshare.rs` (and update keygen tests to use that instead of hand-calculating). See also #340 
- [x] Redact private key share from debug impl (see #163)
- [ ] Maybe add curve point generation to the `CurvePoint` module. If not, make a separate issue to revisit that API.

**Comment by hridambasu** [comment]
@marsella Can you make members of a public struct in Rust read-only? I think it might not be possible? If yes, shall I use #[readonly::make] before the struct definition?

**Comment by marsella** [comment]
Ah, when I say read-only, I mean make the fields private but add public getter methods, like this:

```rust
struct PublicThing {
    foo: u8,
    bar: Vec<u8>,
}

impl PublicThing {
    pub fn foo(&self) -> &u8 {
        &self.u8
    }
}
```

The idea is that callers can still access `foo` but they can't separate it from `PublicThing` (because you only get back a reference) and they can't arbitrarily change it, in case there's some relationship between `foo` and `bar` that we want to preserve (e.g. we've defined an invariant on the fields of `PublicThing` and we don't want external users of the library to be able to break it).

See the `identifier`/`from`/`to` fields on `Message` as another example.
```
