### ISSUE TITLE
test_chinese_remainder_theorem() has a small chance of failing 

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#24]
As shown in this CI run: https://github.com/boltlabs-inc/tss-ecdsa/actions/runs/3430896811/jobs/5718398191
The test should be modified to minimize the chance of interference with unrelated CI runs.

To close this issue, we should
- [ ] figure out what properties the CRT inputs need to satisfy
- [ ] In the happy test, validate them before calling the function.
- [ ] Add failure-case tests to make sure when those properties aren't satisfied, the CRT fails.

**Comment by marsella** [comment]
We should figure out if there are any properties that the inputs to the CRT need to satisfy, and write some negative tests for those.

**Comment by marsella** [comment]
@tyurek floated a theory while discussing #35 that this may have been caused by accidentally generating two matching safe primes.
