### ISSUE TITLE
Update proof context to include ECDSA and Paillier parameters

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#240]
The `Context` for keygen, auxinfo, and presign should include all fixed cryptographic parameters, including the ECDSA parameters `(G, g, q)` and the size of the Paillier key.

This does not have to be added to broadcast's context.

- [ ] Decide a canonical representation for these fields. If appropriate, you could add a method to `parameters.rs` to define the encoding.
- [ ] Add them to the `Context` type for each of the three protocol participants
- [ ] Return them from the `context()` method using your canonical representation
- [x] Make the `impl ProofContext for ()` compile for tests only.

**Comment by Ra1issa** [comment]
I estimate that this will take me 2-3 hours.
