### ISSUE TITLE
Consider deletion behavior for completed participants

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#250]
Once a `Participant` returns output, it is done (see #160). At this point, the calling application can safely drop it. We don't necessarily want to manually drop the participant within the library though, since the calling application may want to keep it for a little while to handle identifiable abort (once we implement that, and if someone else has a problem).

I think it's useful to have some kind of explicit method for the calling application to use when they're done with the `Participant`.

Maybe reference [this blog about correct zeroize usage](https://benma.github.io/2020/10/16/rust-zeroize-move.html) to make sure we're doing it correctly.

- [ ] Define a deletion method (implement `Drop`?) that consumes a `Participant` and manually zerioizes all its sensitive memory.
- [ ] Maybe add a corresponding method to `PublicProtocolParticipant` to call into, since `Participant` itself doesn't manage its intermediate memory.

**Comment by marsella** [comment]
@gatoWololo is this a reasonable approach for deletion?

**Comment by gatoWololo** [comment]
This is an interesting problem! I have read the blog you shared, as well as the `zeroize` and `secrecy` crates.

My main thought:
>  Define a deletion method (implement Drop?) that consumes a Participant and manually zerioizes all its sensitive memory.

I don't think we should manually zeroize fields in `Participant`s structs. We should instead take a "bottom up approach" where sensitive types is wrapped with `zeroize` or `secret`. So a `Participant` (or any other usage of a sensitive type) will automatically have their values zeroized whenever they are dropped.

After reading through the blog post provided, there is a few things we need to handle:
- It seems moving a stack-allocated value may cause copies to be made. This includes: assigning a value to a variable, returning a value from a function, setting a field in a struct, etc.
- Pushing to a string or vec may cause it to be reallocated.

The first bullet point seems particularly tricky and error prone for developers of this crate to always get right. So I propose we do the following:
- Identify which values/types should be treated as secret.
- Use the `secrecy` crate to wrap these secret types in a `Secret<T>` (or use the provided `secret` types if they apply).
- Ensure all our secret values are heap-allocated.

These will act as our "primitive" secret types. These primitives can freely be used in structs or functions, their secret-wrapper will ensure they do the right thing when being used/moved/dropped. So composite types, like `Participant` don't have to think about the details.

We should have a short discussion about this!

**Comment by marsella** [comment]
Okay great, thanks for reviewing this so carefully! I like the bottom-up approach and have been trying a bit to move us in that direction. With #263, we did apply `ZeroizeOnDrop` to all the types that I think are secret (and manually implemented redacted debugging, since I didn't realize the crate would do that for us...). Then the remaining work would be to make sure all of those types are heap-allocated and wrapped in `Secret`s appropriately. 

I'll ping you separately to schedule a discussion on this.

**Comment by marsella** [comment]
I made #330 and #331 to start addressing this. See also the excellent notes about dealing with secrets in a product library in boltlabs-inc/key-mgmt#512.

I think for libraries owned by the cryptography team, using the `secrecy` crate is less helpful, since we _do_ interact with the secret types all the time; unlike product libraries that will hopefully be able to use secret types in a black-box way, I think it'll be super un-ergonomic to have to `expose_secret` every time we do basic operations.

I'm going to close this issue because I don't think we'll take it on as-is, but please feel free to continue discussion if there are further issues that should spawn out of this topic.
