### ISSUE TITLE
Change signing API

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#251]
Now that signing uses an external record instead of looking in the `Participant`'s storage, it's a bit of an awkward method -- it doesn't use any data from the `Participant`! It's also weird to have to call it from a `Participant` paramaterized by a different subprotocol. Instead, let's remove that method and just call `sign` on the `PresignRecord` directly.

- [x] Remove the `sign` function from `Participant`
- [x] Update the return type of `PresignRecord::sign` to return a `SignatureShare` like the other sign function did
- [x] Update `PresignRecord::sign` to consume the record, and make the method public
- [x] Update `SignatureShare` API to make `r` and `s` private
- [ ] Update tests and examples to work with this change

**Comment by gatoWololo** [comment]
Additionally, the `sign` function takes the `Sha256` type directly. Instead it should take a hash.

[See this comment.](https://github.com/boltlabs-inc/tss-ecdsa/pull/302#discussion_r1172049800)

**Comment by hridambasu** [comment]
PresignRecord::sign method is already public - pub(crate). Should I remove the crate?

**Comment by marsella** [comment]
> PresignRecord::sign method is already public - pub(crate). Should I remove the crate?

`pub(crate)` means it's public to any type in the crate, but not externally. We want it to be public externally, so yes, plain `pub`. See the [rust book chapter on visibility](https://doc.rust-lang.org/reference/visibility-and-privacy.html) for more context.
