### ISSUE TITLE
Update `KeyShare` types to have conversion functions to `PiSch` types

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#285]
Currently, in `KeygenParticipant`, we manually construct the necessary `PiSch...` types from the corresponding `KeyShare...` types. It would be cleaner if that was hidden within a `From` or `TryFrom` `impl`.

I believe we want the following `impl`s:
- [ ] `From<KeySharePublic> for PiSchInput`
- [ ] `TryFrom<KeySharePublic> for PiSchProof`
- [ ] `From<KeySharePrivate> for PiSchSecret`

**Comment by marsella** [comment]
Are there additional tests that should spawn out of this change? I'm thinking about an invariant like, "a pisch proof constructed from a valid public/private key share pair should always pass". But this may be effectively satisfied by the existing tests in the pisch module.

**Comment by marsella** [comment]
Also, I'm not as sure about the second one. A `PiSchProof` is a function of an input, a transcript, a context, and a secret, and doesn't feel like a good candidate for the simple `TryFrom` interface to me. I previously suggested `PiSchPrecommit`, but that also requires an RNG, so `From` would be a bit simplistic.
