### ISSUE TITLE
Replace output of `other_ids` from `&Vec<>` to `&[]`

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#292]
Currently, `InnerProtocolParticipant::other_ids` returns a `&Vec<>`, whereas returning a `&[]` is more standard.

# Tasks
- [x] Replace output of `InnerProtocolParticipant::other_ids` from `&Vec<>` to `&[]`.
- [x] Update calls to this method as necessary.

**Comment by hridambasu** [comment]
I don't see the function implemented separately for InnerProtocolParticipant. Shall I change the output type of the function implemented in ProtocolParticipant from `&Vec<>` to `&[]`?

**Comment by marsella** [comment]
Yes please! It might have gotten moved around since the issue was written, but the general problem was that `&Vec` is not the Rustiest way to return values.
