### ISSUE TITLE
Pass context to pisch precommitment proofs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#299]
When we addressed #237 or #238, we missed one case where a ZK proof needs to take context as a parameter instead of instantiating it itself. This is in `pisch`, which has an interface that doesn't quite match the standard `Proof` template. Because of the way it's used in the proof, it's broken into three phases: precommit, prove, and verify.

In fact, the `verify` method on the `PiSchProof` is never used right now, despite correctly using a transcript and context! There's a `verify_with_transcript` method instead that should have been replaced in an earlier refactor.

- [ ] Update `PiSchProof::prove_from_precommit` function to take context as a parameter
- [ ] Get rid of the `verify_with_transcript` method, since it should do exactly the same thing now that `verify` also takes a transcript. Make sure the final function takes context as a parameter
- [ ] Mark the implementation of the `ProofContext` trait for `()` as test-only

**Comment by Ra1issa** [comment]
My first estimate is that this should take me 1-2 hours.
