### ISSUE TITLE
Add Logging Framework to Project

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/tss-ecdsa#31]
We have ran into a few places where proper logging would be useful for debugging errors.

I recommend using the [tracing](https://docs.rs/tracing/latest/tracing/) library. We will be using this in the lock-keeper project. Perhaps hold off until that is implemented (this week) so we can use that as an example.

Long term, we probably want to add logging to various places in the code (the most important/interesting operations or errors). A good place to start would be the unit tests, which already are writing to standard output.

Tasks:
- [x] Add tracing as a dependency and pick an appropriate consumer. (Wait until lock-keeper testing is set up and use that as a template).
- [x] Change unit tests to use logging framework.
- [x] Update CI to run with logging on for unit tests.

**Comment by marsella** [comment]
@gatoWololo Is the logging in lock-keeper working well enough to use as an example for this repo?

**Comment by gatoWololo** [comment]
Yes, I have been meaning to link to it. You can [see here](https://github.com/boltlabs-inc/key-mgmt/pull/380) for the PR that implements logging for lock-keeper.

I also want to bring attention to `bin/key-server-cli/src/main.rs` which now has a thorought explanation of tracing concepts and how to use it. I recommend looking at this via `cargo doc --open` for the nicely formatted version.
