### ISSUE TITLE
Measure tss-ecdsa Execution Time with Networking

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/tss-ecdsa#318]
This epic aims to create a mini tss-ecdsa sample application to measure the expected cost of our library. We will build off the multi-threaded example #302 to create a set of participants and server that communicate via a network using TCP. This will allow us to estimate the cost of executing our protocol plus networking.

**Comment by marsella** [comment]
@gatoWololo Can we close this now?

**Comment by gatoWololo** [comment]
Yes
