### ISSUE TITLE
Audit content of ZKPs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#368]
When cleaning up several of the zero-knowledge proofs, we identified fields that were part of the proofs that should not have been -- typically, these were masks of secret values whose presence in the proof broke the security.

Review the remaining proofs for adherence to the paper description. Look over the `Proof` types and make sure that every field is explicitly sent from the prover to the verifier in the proof description (with the exception of the challenge).

- [x] audit pifac
- [x] audit pimod
- [x] audit pisch

**Comment by marsella** [comment]
@hridambasu If you find issues, could you please make separate PRs for each proof?

**Comment by hridambasu** [comment]
sure

**Comment by marsella** [comment]
@hridambasu and I both looked at this issue and did not find any issues.

`pimod` and `pifac` both match the paper exactly.

`pisch` includes the private `alpha` value in the `Precommit` type. This seems to be out of convenience: the actual precommitted value is only `A = g^alpha`, but the prover needs access to `alpha` in the response phase of the proof. I think the `Precommit` type includes `alpha` in order to save it for later. We reviewed the uses of the type and `alpha` does not appear to be used incorrectly. At most, this suggests some future API change to make the behavior clearer.
