### ISSUE TITLE
Create a signing module

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#422]
In order to implement the signing algorithms, we'll need to create an `sign` module with the outline of the types we'll need. In this issue, we'll just set up the outline and scaffolding for that implementation -- defining associated types but not any implementation details.

I'm not sure what the best approach is for supporting both interactive and non-interactive signing. Since they use the same underlying protocol, I'm inclined to keep them together in one module, which will include
- the non-interactive signing protocol participant, which just implements the signing protocol from figure 8
- the interactive signing protocol participant, which calls in succession the presign protocol + the non-interactive signing protocol

For now, outline a type for _non-interactive_ signing that implements `ProtocolParticipant` where:
   - input:  A message (`&[u8]`) plus a `PresignRecord`
   - output: The internal signature type defined in #378
   - `todo!()` implementations for all the trait methods
 
## Closing criteria
- [x] Make a new module
- [x] Define the input type as above
- [x] Define the participant type as above

**Comment by indomitableSwan** [comment]
Can you be more specific as to what you mean by "implement the signing protocol"? i.e., are you trying to cover both the three-round interactive and non-interactive protocols from CGGMP20?

**Comment by indomitableSwan** [comment]
> I can expand on that in the relevant issue; this only covers setting up implementation infrastructure (e.g. doing a bunch of gruntwork to instantiate traits and make the module) for interactive signing. I've clarified which signing protocol it is in the description.
> 
> For this issue, nothing is going to be implemented and the expected behavior is that everything panics because we haven't done the protocol yet. I don't want to repeat the behavior of the signing protocol in every issue, but is there a place you think I should put it that will make it clearer what's supposed to happen here?

You've made the scope much clearer now in the description. I would advise adjusting the title to be more informative, too, i.e. "_interactive_ signing module"
