### ISSUE TITLE
Improve code quality for PiModProof

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#50]
Note: This issue has expanded significantly since it was first written; it might be appropriate to break it into several separate issues.

---

There are several code quality issues around `PiModProof`s.

- [x] Add documentation to `PiModProof` with the statements that are being proved
- [x] Update field types in proof, proof elements, input, and secret to more meaningful types where possible
- [x] Update field names in proof, proof elements, input, and secret to have more context, and add the short names in field docs.
- [x] ~in new functions, take cloned parameters by value, not by reference.~ not necessary pending #135 
- [x] In `prove()`, I'd prefer something using an iterator over the for loop + push-to-`Vec` construction there now
- [x] Replace direct indexing (`x[0]`) with handle-able call to `x.get(0)?`
- [x] Add documentation to `y_prime_combinations` to explain the third output (`Vec<BigNumber>`) and why it's okay to only use the first element in that list in practice
- [x] In the tests, for internal facing functions (e.g. `chinese_remainder_theorem`), change asserts checking a specific error type to plain checks that `is_err`. We simplified the error scheme but not the checks here.
- [x] Align type names with other refactored ZKPs, including changing input + secret names to `CommonInput` and `ProverSecret`
- [ ] In arithmetic functions, determine when a failure is an actual customer-facing error vs an expected internal error, and try to refactor to use `Option`s in the latter case. [See comment](https://github.com/boltlabs-inc/tss-ecdsa/pull/235#discussion_r1142645045). This might be big enough to be its own issue / PR.

**Comment by marsella** [comment]
Tentative blocker on #49 to avoid divergence between `prove` and `prove_with_transcript`.

**Comment by marsella** [comment]
If this gets done before #40, add a list of types that should be `ZStarN` on that issue for easy reference.

**Comment by hridambasu** [comment]
refactored the issue to write a separate issue for the last task: https://app.zenhub.com/workspaces/mpc-634d77590ce10a0015f1505b/issues/gh/boltlabs-inc/tss-ecdsa/419
