### ISSUE TITLE
Update Paillier moduli to be 2048-bits

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/tss-ecdsa#55]
Currently the Paillier moduli are 1024-bits, which provides insufficient security (80 bits) against known attacks. To fix this issue, update the key generation method for Paillier to produce a 2048-bit modulus instead. This gives us a default security level (for the uses of Paillier in this protocol) of about 112 bits.

**Comment by indomitableSwan** [comment]
A good reference: https://www.keylength.com/

**Comment by tyurek** [comment]
Three questions:
1) Is 112 the general security level we're aiming for for this whole project, or is this mainly an issue with factoring-related problems?
2) Does it make sense to still use 512 for testing?
3) Do we want external users to be able to specify the prime size?

**Comment by indomitableSwan** [comment]
> Three questions:
> 
> 1. Is 112 the general computational security level we're aiming for for this whole project, or is this mainly an issue with factoring-related problems?

Right now it's sufficient to set the modulus to be 2048-bits, to avoid having an insecure parameter choice hardcoded in the repository. We may decide to increase the size of the modulus further in the future based on our use case.

> 2. Does it make sense to still use 512 for testing?

No.

> 3. Do we want external users to be able to specify the prime size?

Not at this time. We may decide to do this as an additional feature, but if we go down this path, we will want to unify the security levels with ECDSA in order to make this misuse resistant.

**Comment by indomitableSwan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MPC-634d77590ce10a0015f1505b/issues/boltlabs-inc/tss-ecdsa/55?planning-poker) with Zenhub @marsella
