### ISSUE TITLE
Remove `assert` Calls in Non-test Code

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/tss-ecdsa#57]
The codebase uses `assert!`, `assert_eq!`, etc. In general I like checking invariants like this, but we want to avoid panicking at runtime.

We should remove uses of asserts and replace them with either:
- Return an error using our `InternalInvariantFailed` variant.
and/or
- Replace assert with [`debug_assert`](https://doc.rust-lang.org/std/macro.debug_assert.html) which only executes during debug mode.

Note we can combine both: I.e. use the former for easy/fast checks that should always be done, even on the critical path, and use `debug_assert`s for expensive checks.

**Comment by marsella** [comment]
As with #39, we want to remove these from the main library, but they're okay in tests and the current example, right?

**Comment by gatoWololo** [comment]
Yes! asserts are encourged in tests. Probably the best way to check conditions in tests.
