### ISSUE TITLE
Remove crate-defined bail macro and string errors.

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/tss-ecdsa#58]
The code has a lot of uses of stringly typed error variants. E.g. `bail!("Cannot produce a signature without including shares")`.

- [ ] We should remove the bail macro and replace all uses with returning errors from our `InternalError` enum.
- [ ] We should rename this error enum to something more useful.

I recommend the [`thiserror`](https://docs.rs/thiserror/latest/thiserror/) crate which provides "a convenient derive macro for the standard library’s [std::error::Error](https://doc.rust-lang.org/std/error/trait.Error.html) trait". This crate is easy and lightweight to use for defining our own error type.

**Comment by marsella** [comment]
If we turn `InternalError` into a `thiserror` type, I think we can make two improvements:
- Remove the `displaydoc` dependency.
- Replace the `From<PaillierError>` implementation with a `#[from(...)]` flag.
