### ISSUE TITLE
Enforce PaillierCiphertexts in the Paillier API

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#59]
The Paillier encryption and decryption API encodes ciphertexts as `BigNumber`s. 

In most cases, the ciphertexts are used (encoded either as `BigNumber`s or `PaillierCiphertext`s) in a zk proof after generation. In the interest of keeping this PR a manageable size, let's _not_ change the proof types that take a `BigNumber` that should be a ciphertext. That change can be handled in ~the corresponding code-quality issues (e.g. #44, #46, #48, #51, #47, #50
 #52)~ the collective issue #63.

- [x] Update the encrypt and decrypt functions in the Paillier module to return and take `PaillierCiphertexts` directly.
- [ ] Check if it's feasible to reduce the visibility of the `PaillierCiphertext`'s internal `BigNumber`. Can it be made read-only (private with a public accessor method)?

**Comment by marsella** [comment]
Depending on how this change cascades through the library, it might make sense to make a single PR for both this and #63, so we can more clearly see how this is used in practice.

**Comment by amaloz** [comment]
Closed by PR #98
