### ISSUE TITLE
Update Paillier nonce type

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#62]
The Paillier encryption function returns a ciphertext and a nonce. The nonce isn't used for decryption. It's only used to generate zk proofs related to the ciphertext. 

The nonce is currently encoded as a `BigNumber`. It should be wrapped in a more descriptive type, so proofs that use it can be more explicit about what it's supposed to do. Document any additional constraints on it (I think it's in `Z*_N`).

This type is used in the `PiEnc` proof, the `PiLog` proof, and the `PiAffg` proof. Update the relevant proof structs to take the new nonce type instead of a plain `BigNumber`.

**Comment by marsella** [comment]
It might also be reasonable to just use whatever `ZStar` type we settle on in #40, rather than having a Paillier-specific `Nonce`.

**Comment by amaloz** [comment]
Is there a requirement that the nonce be non-zero? I see a check [here](https://github.com/boltlabs-inc/tss-ecdsa/blob/main/src/presign/participant.rs#L934) but no where else. (maybe this gets to your `Z*_N` comment)

**Comment by marsella** [comment]
Yep, see [Definition 2.2 on the bottom of page 16](https://eprint.iacr.org/2021/060.pdf). The nonce ρ is drawn from `Z*_N`, so it has to be non-zero and coprime to the Paillier modulus `N`.
