### ISSUE TITLE
Update Pailler ciphertext type in proofs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#63]
Update any proofs that expect Paillier ciphertexts as input to encode those explicitly, rather than as BigNumbers. I spotted some by following the encryptions, but double-check the other proof types to make sure they don't have any.

- PiAffg (Paillier Operation with Group Commitment in Range ZK): input Y is a ciphertext. Maybe other inputs are also ciphertexts.

- PiEnc (Paillier Encryption in Range ZK): input K is a ciphertext, but this is already encoded!

- PiLog (Knowledge of Exponent vs Paillier Encryption): I think input C is a ciphertext, but the proof definition (Fig 25) is kind of vague on this.

This handles some tasks also described in #44, #46, and #48.

**Comment by amaloz** [comment]
Note: Check if it's feasible to reduce the visibility of the `PaillierCiphertext`'s internal `BigNumber` alongside this change.
