### ISSUE TITLE
Pull Paillier + and * into Paillier module

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#64]
Currently, proofs that need to use Paillier operations (like adding two ciphertexts together or multiplying a ciphertext by a constant) use the operations directly from the underlying Paillier library. To simplify that code and make it easier to potentially switch out the Paillier dependency, we should abstract those operations into the Paillier module.

- [ ] Make a * and + operation in the Paillier module that operate on our library-specific wrapper types.
- [ ] Remove all direct accesses to the libpaillier encryption keys outside of the Paillier module (if this reveals other operations that require a new API, make another issue)
- [ ] Try to make `Paillier{Encryption|Decryption}Key` inner types private

**Comment by amaloz** [comment]
Note: Check if it's feasible to reduce the visibility of the `PaillierCiphertext`'s internal `BigNumber` alongside this change.

**Comment by marsella** [comment]
We can also consider simplifying our Paillier module API further. It looks like we only add and multiply ciphertexts in presigning, and the operation is always of the form `a*C1 + C2` (e.g. multiply by a scalar, then add two ciphertexts). So instead of revealing addition and multiplication independently, we could just have one `multiply_and_add` kind of function.

**Comment by amaloz** [comment]
> It looks like we only add and multiply ciphertexts in presigning, and the operation is always of the form a*C1 + C2 (e.g. multiply by a scalar, then add two ciphertexts).

Don't we also have `C1 * C2^e` in some of the ZKPs?

That being said, I think a `multiply_and_add` and an `exponentiate_and_multiply` might be the least error prone from an API perspective.

**Comment by amaloz** [comment]
Whoops! I should have realized this, but the operation `a * C1 + C2` in the ciphertext domain is computed as `C1^a * C2`, so there really should be only `multiply_and_add`.
