### ISSUE TITLE
Ignore slow test until push to main

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#65]
The `run_auxinfo_protocol_many_times` test takes ages and it makes it hard to run the CI tests locally because you can't just throw down 'cargo make ci`. 

Can we ignore that test normally and only run it on merge to main, instead of every test run? We already have a test that auxinfo works once in the normal test suite, this one is more of a double-check and I think doesn't need to be run constantly.

**Comment by gatoWololo** [comment]
Yes, we should be using the `#[ignore]` compiler directive on this test:
```rust
#[test]
#[ignore]
fn expensive_test() {
    // code that takes an hour to run
}
```
`cargo test` will ignore this test, which is what we should use for the CI when not running on the main branch. Then, we can use `cargo test -- --ignored` to run all tests on `main`. There should be a way to set this up via our Github Action to get them to call the right command.
