### ISSUE TITLE
Test Concurrent Sessions

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#9]
Any protocol or subprotocol implementation should include a test case which ensures that multiple protocol sessions happening in parallel do not interfere with each other.

This may not be an issue if we stick to the practice of using Storage to manage all internal state variables, but it could be a good safeguard to have nonetheless.

This issue can be closed when we have additional tests that concurrent runs of each subprotocol run successfully.

**Comment by marsella** [comment]
Closing this issue; the API change that makes each `Participant` run only a single session removes the need to test this.
