### ISSUE TITLE
Clarify networking requirements

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#93]
The threshold-ECDSA protocol requires two types of communication channels: point-to-point and broadcast. The tss-ecdsa library does not (and should not!) implement any networking; it returns messages after each protocol round that the calling application is responsible for sending over a point-to-point channel. It has special support for broadcast and implements an echo broadcast functionality (again, doing the checks but not the networking).

Goals of this epic:
- [x] Document networking requirements at the crate level, so calling applications understand what they need to provide to have a correct protocol implementation.
- [x] Eliminating this task from this epic; we'll make a separate epic when we're ready to address it. ~Reconsider the broadcast API. A valid broadcast channel is a security-critical element of the protocol, which is likely why a specific implementation was included in the tss-ecdsa library. However, since we use this library as part of a larger protocol, it may be reasonable to leave it up to the calling application to determine how to implement the broadcast channel. If we take this approach, we should carefully document what a cryptographically-secure broadcast channel is and provide references on how to implement it. We can also consider tagging output messages more carefully to indicate what kind of channel they should be sent over.~

**Comment by indomitableSwan** [comment]
If we determine that the library should include a broadcast implementation in order to provide appropriate misuse resistance, we may also have to offer an additional option for realizing the broadcast channel.

**Comment by marsella** [comment]
The scope of this was reduced to adding documentation about the current requirements; further networking improvements will get their own epics as they become more clearly defined. Closing!!
