### ISSUE TITLE
Change API of `PaillierEncryptionKey::encrypt` to allow verification

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#99]
Currently the API of `PaillierEncryptionKey::encrypt` is as follows:
```rust
pub(crate) fn encrypt<R: RngCore + CryptoRng>(
        &self,
        rng: &mut R,
        x: &BigNumber,
    ) -> Result<(BigNumber, BigNumber)>
```
That is, the output is a ciphertext and nonce.

Unfortunately, this API does not work when needing to _validate_ encryptions (as is done in both `pilog` and `pienc`), where the nonce needs to be supplied as input and encryption is entirely deterministic (no use of an RNG). This leads to manually computing the encryption as part of the ZKPs (e.g., see [here](https://github.com/boltlabs-inc/tss-ecdsa/blob/main/src/zkp/pilog.rs#L186)), which is potentially error-prone and less modular.

# Proposed Solution

Here is one proposed solution, but I'm open to others. First, we have an enum that marks whether we're a prover or a verifier:
```rust
pub(crate) enum PaillierEncryptionRole<'a, R: RngCore + CryptoRng> {
    Prover(&'a mut R),
    Verifier(&'a BigNumber),
}
```
Then, the `encrypt` API becomes:
```rust
    pub(crate) fn encrypt<R: RngCore + CryptoRng>(
        &self,
        x: &BigNumber,
        role: PaillierEncryptionRole<R>,
    ) -> Result<(PaillierCiphertext, BigNumber)>
```
Now, we can generate a nonce as needed, or use the nonce provided.

One downside of this approach is that when using encryption in "verifier-mode", we need to supply _some_ RNG type to make rust happy, e.g.,:
```rust
PaillierEncryptionRole::Verifier::<StdRng>(&value)
```
which isn't too nice from an API perspective. Is there a cleaner workaround for that?

**Comment by amaloz** [comment]
As suggested by @marsella, a much simpler approach would be to add:
```rust
pub(crate) fn encrypt_verify(&self, x: &BigNumber, nonce: &BigNumber) -> Result<PaillierCiphertext>
```
which could be called when verification is needed.

**Comment by marsella** [comment]
I think my main concern in either of these solutions is that callers know when to use each one. The benefit of the first approach is that it includes an explicit role, but reasonable documentation and naming will help with the second approach. After we do #62, we might also get a bit of misuse resistance in the simpler approach by not having a manual nonce-creation method. So, if a caller isn't sure which encryption function to use but they don't have a `Nonce`, that's a good sign that they should use plain `encrypt` and not `encrypt_verify`.
